version: '3'

services:
  pal:
    container_name: pal
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    stop_grace_period: 30s
    tty: true
    volumes:
      - ./palworld:/palworld/
    environment:
      TZ: Asia/Tokyo
      PUID: 1000
      PGID: 999
      PORT: 8211
      PLAYERS: 32
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      COMMUNITY: false
      SERVER_NAME: "TEST"
      SERVER_DESCRIPTION: "Test in Docker"
      DISCORD_WEBHOOK_URL: ${WEBHOOK}
      BACKUP_ENABLED: false
    ports:
      - "${PORT}:8211/udp"
      - "${RCON_PORT}:25575/tcp"
    healthcheck:
      test: rcon-cli info

  dgln:
    container_name: dgln
    image: ghcr.io/mizunanari/dgln:latest
    restart: always
    tty: true
    depends_on:
      pal:
        condition: service_healthy
    environment:
      DGLN_DISCORD_WEBHOOK_URL: ${WEBHOOK}
      DGLN_RCON_ADDRESS: pal
      DGLN_RCON_PORT: 25575
      DGLN_RCON_PASSWORD: ${ADMIN_PASSWORD}
      DGLN_LOOP_INTERVAL_SEC: 5
      DGLN_LOG_FILEPATH: player_log.json
